/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardConnectionsRouteImport } from './routes/dashboard.connections'
import { Route as DashboardTriggersRouteImport } from './routes/dashboard.triggers'
import { Route as DashboardExecutionsIndexRouteImport } from './routes/dashboard.executions.index'
import { Route as DashboardExecutionsIdRouteImport } from './routes/dashboard.executions.$id'
import { Route as DashboardToolkitsIndexRouteImport } from './routes/dashboard.toolkits.index'
import { Route as DashboardToolkitsSlugRouteImport } from './routes/dashboard.toolkits.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConnectionsRoute = DashboardConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTriggersRoute = DashboardTriggersRouteImport.update({
  id: '/triggers',
  path: '/triggers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExecutionsIndexRoute =
  DashboardExecutionsIndexRouteImport.update({
    id: '/executions/',
    path: '/executions/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardExecutionsIdRoute = DashboardExecutionsIdRouteImport.update({
  id: '/executions/$id',
  path: '/executions/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardToolkitsIndexRoute = DashboardToolkitsIndexRouteImport.update({
  id: '/toolkits/',
  path: '/toolkits/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardToolkitsSlugRoute = DashboardToolkitsSlugRouteImport.update({
  id: '/toolkits/$slug',
  path: '/toolkits/$slug',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/connections': typeof DashboardConnectionsRoute
  '/dashboard/triggers': typeof DashboardTriggersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/executions/$id': typeof DashboardExecutionsIdRoute
  '/dashboard/toolkits/$slug': typeof DashboardToolkitsSlugRoute
  '/dashboard/executions/': typeof DashboardExecutionsIndexRoute
  '/dashboard/toolkits/': typeof DashboardToolkitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/connections': typeof DashboardConnectionsRoute
  '/dashboard/triggers': typeof DashboardTriggersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/executions/$id': typeof DashboardExecutionsIdRoute
  '/dashboard/toolkits/$slug': typeof DashboardToolkitsSlugRoute
  '/dashboard/executions': typeof DashboardExecutionsIndexRoute
  '/dashboard/toolkits': typeof DashboardToolkitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/connections': typeof DashboardConnectionsRoute
  '/dashboard/triggers': typeof DashboardTriggersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/executions/$id': typeof DashboardExecutionsIdRoute
  '/dashboard/toolkits/$slug': typeof DashboardToolkitsSlugRoute
  '/dashboard/executions/': typeof DashboardExecutionsIndexRoute
  '/dashboard/toolkits/': typeof DashboardToolkitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/connections'
    | '/dashboard/triggers'
    | '/dashboard/'
    | '/dashboard/executions/$id'
    | '/dashboard/toolkits/$slug'
    | '/dashboard/executions/'
    | '/dashboard/toolkits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/connections'
    | '/dashboard/triggers'
    | '/dashboard'
    | '/dashboard/executions/$id'
    | '/dashboard/toolkits/$slug'
    | '/dashboard/executions'
    | '/dashboard/toolkits'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/connections'
    | '/dashboard/triggers'
    | '/dashboard/'
    | '/dashboard/executions/$id'
    | '/dashboard/toolkits/$slug'
    | '/dashboard/executions/'
    | '/dashboard/toolkits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/connections': {
      id: '/dashboard/connections'
      path: '/connections'
      fullPath: '/dashboard/connections'
      preLoaderRoute: typeof DashboardConnectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/triggers': {
      id: '/dashboard/triggers'
      path: '/triggers'
      fullPath: '/dashboard/triggers'
      preLoaderRoute: typeof DashboardTriggersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/executions/': {
      id: '/dashboard/executions/'
      path: '/executions'
      fullPath: '/dashboard/executions/'
      preLoaderRoute: typeof DashboardExecutionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/executions/$id': {
      id: '/dashboard/executions/$id'
      path: '/executions/$id'
      fullPath: '/dashboard/executions/$id'
      preLoaderRoute: typeof DashboardExecutionsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/toolkits/': {
      id: '/dashboard/toolkits/'
      path: '/toolkits'
      fullPath: '/dashboard/toolkits/'
      preLoaderRoute: typeof DashboardToolkitsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/toolkits/$slug': {
      id: '/dashboard/toolkits/$slug'
      path: '/toolkits/$slug'
      fullPath: '/dashboard/toolkits/$slug'
      preLoaderRoute: typeof DashboardToolkitsSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardConnectionsRoute: typeof DashboardConnectionsRoute
  DashboardTriggersRoute: typeof DashboardTriggersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardExecutionsIdRoute: typeof DashboardExecutionsIdRoute
  DashboardToolkitsSlugRoute: typeof DashboardToolkitsSlugRoute
  DashboardExecutionsIndexRoute: typeof DashboardExecutionsIndexRoute
  DashboardToolkitsIndexRoute: typeof DashboardToolkitsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConnectionsRoute: DashboardConnectionsRoute,
  DashboardTriggersRoute: DashboardTriggersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardExecutionsIdRoute: DashboardExecutionsIdRoute,
  DashboardToolkitsSlugRoute: DashboardToolkitsSlugRoute,
  DashboardExecutionsIndexRoute: DashboardExecutionsIndexRoute,
  DashboardToolkitsIndexRoute: DashboardToolkitsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
